# Generated by Django 3.1.2 on 2020-10-30 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageHash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_email', models.TextField()),
                ('to_email', models.TextField()),
                ('i_hash', models.TextField()),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
