# Generated by Django 3.1.2 on 2020-10-30 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagehash',
            name='from_email',
        ),
        migrations.RemoveField(
            model_name='imagehash',
            name='to_email',
        ),
        migrations.AlterField(
            model_name='imagehash',
            name='i_hash',
            field=models.TextField(unique=True),
        ),
    ]
